# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: discovery.knative.dev/v1alpha1
kind: ClusterDuckType
metadata:
  name: bindings.duck.knative.dev
  labels:
    discovery.knative.dev/release: devel
spec:
  selectors:
    - labelSelector: "duck.knative.dev/binding=true"

  names:
    name: "Binding"
    plural: "bindings"
    singular: "binding"

  versions:
    - name: "v1beta1"
      additionalPrinterColumns:
        - name: Subject Kind
          type: string
          jsonPath: .spec.subject.kind
        - name: Subject Name
          type: string
          jsonPath: .spec.subject.name

      # schema: # TODO
    #// BindingSpec specifies the spec portion of the Binding partial-schema.
    #  type BindingSpec struct {
    #  // Subject references the resource(s) whose "runtime contract" should be
    #  // augmented by Binding implementations.
    #  Subject tracker.Reference `json:"subject"`
    #}
  group: duck.knative.dev
