/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/discovery/pkg/apis/discovery/v1alpha1"
	scheme "knative.dev/discovery/pkg/client/clientset/versioned/scheme"
)

// ClusterDuckTypesGetter has a method to return a ClusterDuckTypeInterface.
// A group's client should implement this interface.
type ClusterDuckTypesGetter interface {
	ClusterDuckTypes() ClusterDuckTypeInterface
}

// ClusterDuckTypeInterface has methods to work with ClusterDuckType resources.
type ClusterDuckTypeInterface interface {
	Create(*v1alpha1.ClusterDuckType) (*v1alpha1.ClusterDuckType, error)
	Update(*v1alpha1.ClusterDuckType) (*v1alpha1.ClusterDuckType, error)
	UpdateStatus(*v1alpha1.ClusterDuckType) (*v1alpha1.ClusterDuckType, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ClusterDuckType, error)
	List(opts v1.ListOptions) (*v1alpha1.ClusterDuckTypeList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterDuckType, err error)
	ClusterDuckTypeExpansion
}

// clusterDuckTypes implements ClusterDuckTypeInterface
type clusterDuckTypes struct {
	client rest.Interface
}

// newClusterDuckTypes returns a ClusterDuckTypes
func newClusterDuckTypes(c *DiscoveryV1alpha1Client) *clusterDuckTypes {
	return &clusterDuckTypes{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterDuckType, and returns the corresponding clusterDuckType object, and an error if there is any.
func (c *clusterDuckTypes) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterDuckType, err error) {
	result = &v1alpha1.ClusterDuckType{}
	err = c.client.Get().
		Resource("clusterducktypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterDuckTypes that match those selectors.
func (c *clusterDuckTypes) List(opts v1.ListOptions) (result *v1alpha1.ClusterDuckTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterDuckTypeList{}
	err = c.client.Get().
		Resource("clusterducktypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterDuckTypes.
func (c *clusterDuckTypes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clusterducktypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a clusterDuckType and creates it.  Returns the server's representation of the clusterDuckType, and an error, if there is any.
func (c *clusterDuckTypes) Create(clusterDuckType *v1alpha1.ClusterDuckType) (result *v1alpha1.ClusterDuckType, err error) {
	result = &v1alpha1.ClusterDuckType{}
	err = c.client.Post().
		Resource("clusterducktypes").
		Body(clusterDuckType).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterDuckType and updates it. Returns the server's representation of the clusterDuckType, and an error, if there is any.
func (c *clusterDuckTypes) Update(clusterDuckType *v1alpha1.ClusterDuckType) (result *v1alpha1.ClusterDuckType, err error) {
	result = &v1alpha1.ClusterDuckType{}
	err = c.client.Put().
		Resource("clusterducktypes").
		Name(clusterDuckType.Name).
		Body(clusterDuckType).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *clusterDuckTypes) UpdateStatus(clusterDuckType *v1alpha1.ClusterDuckType) (result *v1alpha1.ClusterDuckType, err error) {
	result = &v1alpha1.ClusterDuckType{}
	err = c.client.Put().
		Resource("clusterducktypes").
		Name(clusterDuckType.Name).
		SubResource("status").
		Body(clusterDuckType).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterDuckType and deletes it. Returns an error if one occurs.
func (c *clusterDuckTypes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterducktypes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterDuckTypes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clusterducktypes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterDuckType.
func (c *clusterDuckTypes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterDuckType, err error) {
	result = &v1alpha1.ClusterDuckType{}
	err = c.client.Patch(pt).
		Resource("clusterducktypes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
