/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/discovery/pkg/apis/discovery/v1alpha1"
)

// FakeClusterDuckTypes implements ClusterDuckTypeInterface
type FakeClusterDuckTypes struct {
	Fake *FakeDiscoveryV1alpha1
}

var clusterducktypesResource = schema.GroupVersionResource{Group: "discovery.knative.dev", Version: "v1alpha1", Resource: "clusterducktypes"}

var clusterducktypesKind = schema.GroupVersionKind{Group: "discovery.knative.dev", Version: "v1alpha1", Kind: "ClusterDuckType"}

// Get takes name of the clusterDuckType, and returns the corresponding clusterDuckType object, and an error if there is any.
func (c *FakeClusterDuckTypes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterDuckType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterducktypesResource, name), &v1alpha1.ClusterDuckType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterDuckType), err
}

// List takes label and field selectors, and returns the list of ClusterDuckTypes that match those selectors.
func (c *FakeClusterDuckTypes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterDuckTypeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterducktypesResource, clusterducktypesKind, opts), &v1alpha1.ClusterDuckTypeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterDuckTypeList{ListMeta: obj.(*v1alpha1.ClusterDuckTypeList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterDuckTypeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterDuckTypes.
func (c *FakeClusterDuckTypes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterducktypesResource, opts))
}

// Create takes the representation of a clusterDuckType and creates it.  Returns the server's representation of the clusterDuckType, and an error, if there is any.
func (c *FakeClusterDuckTypes) Create(ctx context.Context, clusterDuckType *v1alpha1.ClusterDuckType, opts v1.CreateOptions) (result *v1alpha1.ClusterDuckType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterducktypesResource, clusterDuckType), &v1alpha1.ClusterDuckType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterDuckType), err
}

// Update takes the representation of a clusterDuckType and updates it. Returns the server's representation of the clusterDuckType, and an error, if there is any.
func (c *FakeClusterDuckTypes) Update(ctx context.Context, clusterDuckType *v1alpha1.ClusterDuckType, opts v1.UpdateOptions) (result *v1alpha1.ClusterDuckType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterducktypesResource, clusterDuckType), &v1alpha1.ClusterDuckType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterDuckType), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterDuckTypes) UpdateStatus(ctx context.Context, clusterDuckType *v1alpha1.ClusterDuckType, opts v1.UpdateOptions) (*v1alpha1.ClusterDuckType, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterducktypesResource, "status", clusterDuckType), &v1alpha1.ClusterDuckType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterDuckType), err
}

// Delete takes name of the clusterDuckType and deletes it. Returns an error if one occurs.
func (c *FakeClusterDuckTypes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clusterducktypesResource, name), &v1alpha1.ClusterDuckType{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterDuckTypes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterducktypesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterDuckTypeList{})
	return err
}

// Patch applies the patch and returns the patched clusterDuckType.
func (c *FakeClusterDuckTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterDuckType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterducktypesResource, name, pt, data, subresources...), &v1alpha1.ClusterDuckType{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterDuckType), err
}
