/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	discoveryv1alpha1 "knative.dev/discovery/pkg/apis/discovery/v1alpha1"
	versioned "knative.dev/discovery/pkg/client/clientset/versioned"
	internalinterfaces "knative.dev/discovery/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "knative.dev/discovery/pkg/client/listers/discovery/v1alpha1"
)

// ClusterDuckTypeInformer provides access to a shared informer and lister for
// ClusterDuckTypes.
type ClusterDuckTypeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterDuckTypeLister
}

type clusterDuckTypeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterDuckTypeInformer constructs a new informer for ClusterDuckType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterDuckTypeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterDuckTypeInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterDuckTypeInformer constructs a new informer for ClusterDuckType type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterDuckTypeInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DiscoveryV1alpha1().ClusterDuckTypes().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DiscoveryV1alpha1().ClusterDuckTypes().Watch(context.TODO(), options)
			},
		},
		&discoveryv1alpha1.ClusterDuckType{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterDuckTypeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterDuckTypeInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterDuckTypeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&discoveryv1alpha1.ClusterDuckType{}, f.defaultInformer)
}

func (f *clusterDuckTypeInformer) Lister() v1alpha1.ClusterDuckTypeLister {
	return v1alpha1.NewClusterDuckTypeLister(f.Informer().GetIndexer())
}
