name: Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codecov:
    name: Codecov
    strategy:
      matrix:
        go-version: [1.14.x]

    runs-on: ubuntu-latest

    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code onto GOPATH
      uses: actions/checkout@v2

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Codecov
      uses: codecov/codecov-action@v1
