name: KinD e2e tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ko-resolve:
    name: e2e tests
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
      KO_DOCKER_REPO: kind.local

    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x

    - name: Install Dependencies
      run: |
        echo '::group:: install ko'
        curl -L https://github.com/google/ko/releases/download/v0.7.0/ko_0.7.0_Linux_x86_64.tar.gz | tar xzf - ko
        chmod +x ./ko
        sudo mv ko /usr/local/bin
        echo '::endgroup::'

    - name: Check out code onto GOPATH
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: ./src/knative.dev/discovery

    - name: Install KinD
      working-directory: ./src/knative.dev/discovery
      env:
        KIND_VERSION: v0.8.1
      run: |
        set -x

        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv kind /usr/local/bin

    - name: Create KinD Cluster
      working-directory: ./src/knative.dev/discovery
      run: |
        set -x

        # KinD configuration.
        cat > kind.yaml <<EOF
        apiVersion: kind.x-k8s.io/v1alpha4
        kind: Cluster
        nodes:
        - role: control-plane
        - role: worker
        EOF

        # Create a cluster!
        kind create cluster --config kind.yaml

    - name: Install Knative Discovery
      working-directory: ./src/knative.dev/discovery
      run: |
        set -x

        # Build and Publish our test images to the docker daemon.
        # ./test/upload-test-images.sh # <-- Skip for now.

        # Build and Publish our containers to the docker daemon (including test assets)
        export GO111MODULE=on
        export GOFLAGS=-mod=vendor
        ko apply -Pf config/ -f test/config

    - name: Wait for Ready
      working-directory: ./src/knative.dev/discovery
      run: |
        set -x

        # Probably don't need this anymore, but keep until we
        # have something that waits for pods to becomes ready.
        sleep 60

        # For debugging.
        kubectl get pods --all-namespaces

    - name: Run e2e Tests
      working-directory: ./src/knative.dev/discovery
      run: |
        set -x

        # For logstream to work.
        export SYSTEM_NAMESPACE=knative-discovery

        # Run the tests tagged as e2e on the KinD cluster.
        go test -v -race -count=1 -timeout=3m -tags=e2e ./test/e2e/...

